### PR TITLE
Add farming as optional dependency

### PR DESCRIPTION
**Pull request by louisroyer**
And make the mod working with hoes

### CODE REVIEW

**Comment by lisacvuk** [comment]
This should be added to farming mod, I believe adding dependencies is what caused moreores circular dependency issue.

**Comment by louisroyer** [comment]
Ok, I will do a PR on [mintest-game-mods/farming](https://github.com/minetest-game-mods/farming) instead.

**Comment by lisacvuk** [comment]
I will close this PR then, thank you :)

**Comment by louisroyer** [comment]
[Here is the PR](https://github.com/minetest-game-mods/farming/pull/1) made on farming mod.

**Pull request closed without merging**
