### PR TITLE
Fixed circular dependencies

### PR DESCRIPTION
**Pull request by Ginger88895**

### CODE REVIEW

**Comment by lisacvuk** [comment]
Are you sure making a modpack is the right way to go about this? I feel just removing most of depends.txt would be a better way, then let other mods depend on toolranks

**Comment by Ginger88895** [comment]
Currently I am unaware of any modding conventions that disfavors making this a modpack... Nonetheless, I have tested my changes, so I am certain that it works.

Contacting the authors of "moreores" to move the codes about moreore tools there is also an option.

**Comment by lisacvuk** [comment]
I'm not sure if having moreores in depends.txt is even necessary - maybe I should just revert https://github.com/lisacvuk/minetest-toolranks/commit/cdf26062284c7a3b3c0c771c443824dd829afe71

**Comment by Ginger88895** [comment]
Adding "moreores" to "depends.txt" is necessary as I have just tested it. The game would crash as the tool "moreores:pick_mithril" is not registered yet at the time "toolranks" is loaded.

On a side note, making this a modpack provides modularity, since, in my opinion, there is no reason other mods would need to depend on the non-API part of the mod...

**Comment by lisacvuk** [comment]
> Adding "moreores" to "depends.txt" is necessary as I have just tested it. The game would crash as the  tool "moreores:pick_mithril" is not registered yet at the time "toolranks" is loaded.


Hmm yeah that's right

@tenplus1 whats your input on this?

**Comment by Ginger88895** [comment]
Hello, I suggest that this pull request be merged until a better solution is proposed.

Inferring from their repositories, TenPlus1 is mainly active on [notabug](https://notabug.org); this might be helpful if you wish to contact TenPlus1.

**Pull request closed without merging**
