### PR TITLE
Use tool capabilities and add more levels

### PR DESCRIPTION
**Pull request by OgelGames**
* Changes code to use tool capabilities and `set_tool_capabilities()` to increase speed and durability.
* Adds more levels (10 by default).
* Makes helper function usable by mods that support toolranks.
* Adds settings

### CODE REVIEW

**Comment by lisacvuk** [comment]
Indentation is messed up; it switches from two spaces to four spaces. Aside from that, code looks good, but I haven't tested yet.

**Comment by OgelGames** [comment]
> Indentation is messed up; it switches from two spaces to four spaces.

That was intentional, to switch to tabs instead of spaces, but I can undo that if you want...

**Comment by lisacvuk** [comment]
Please undo, you can make it a separate PR if you want - I personally prefer spaces tho

**Comment by OgelGames** [comment]
Fixed.

**Comment by lisacvuk** [comment]
Thanks :)

**Pull request merged**
